import { StyleSheet } from "react-native";

export const COLORS = {
  primary: "#3B82F6",
  primaryDark: "#2563EB",
  background: "#F3F4F6",
  white: "#FFFFFF",
  textDark: "#1E3A5F",
  textGray: "#6B7280",
  textLight: "#9CA3AF",
  inputBorder: "#3B82F6",
  border: "#E5E7EB",
  inputBg: "#F9FAFB",
  activeBg: "#EFF6FF",
};

export const globalStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.background },

  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },

  heading: { fontSize: 26, fontWeight: "700", color: COLORS.textDark },
  subheading: { fontSize: 14, color: COLORS.textGray, marginTop: 4 },
  label: { fontSize: 12, color: COLORS.textGray, marginBottom: 4, fontWeight: "500" },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: COLORS.textDark, marginBottom: 12 },

  inputContainer: { marginBottom: 16 },
  input: {
    fontSize: 14,
    color: COLORS.textDark,
    borderBottomWidth: 1.5,
    borderBottomColor: COLORS.inputBorder,
    paddingVertical: 8,
  },

  btnPrimary: {
    backgroundColor: COLORS.primary,
    borderRadius: 30,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 8,
  },
  btnPrimaryText: { color: COLORS.white, fontWeight: "600", fontSize: 16 },

  selectBox: {
    backgroundColor: COLORS.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectText: { fontSize: 14, color: COLORS.textDark, fontWeight: "500" },

  dropdown: {
    position: "absolute",
    top: 70,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    zIndex: 999,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  dropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.background,
  },
  dropdownItemActive: { backgroundColor: COLORS.activeBg },
  dropdownText: { fontSize: 14, color: COLORS.textDark },
  dropdownTextActive: { color: COLORS.primary, fontWeight: "600" },

  datePill: {
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 6,
  },
  datePillActive: { backgroundColor: COLORS.activeBg, borderColor: COLORS.primary },
  datePillText: { fontSize: 12, color: COLORS.textGray, fontWeight: "500" },
  datePillTextActive: { color: COLORS.primary, fontWeight: "600" },

  carouselCard: {
    width: 280,
    height: 170,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: COLORS.border,
    marginRight: 12,
  },
  carouselImage: { width: "100%", height: "100%" },
  carouselOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.38)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  carouselName: { color: COLORS.white, fontSize: 15, fontWeight: "700" },
  carouselDesc: { color: "rgba(255,255,255,0.85)", fontSize: 12, marginTop: 2 },

  bottomNav: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.background,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 8,
  },
  bottomNavItem: { flex: 1, alignItems: "center", paddingVertical: 4 },
  bottomNavIcon: { fontSize: 20 },
  bottomNavLabel: { fontSize: 11, color: COLORS.textLight, marginTop: 2 },
  bottomNavLabelActive: { fontSize: 11, color: COLORS.primary, fontWeight: "600", marginTop: 2 },
});